import type { Product, Category } from "./types"
import { Timestamp, FieldValue } from "firebase/firestore"

export const categories: Category[] = [
  {
    id: "1",
    name: "Women",
    image: "/placeholder.svg?height=60&width=60",
    icon: "👗",
    subcategories: ["Midi", "Cargos & Joggers", "Shirts", "Jackets", "Dresses", "Tops"],
  },
  {
    id: "2",
    name: "Men",
    image: "/placeholder.svg?height=60&width=60",
    icon: "👔",
    subcategories: ["Jackets", "Jeans", "Hoodies & Sweatshirts", "Bottoms", "T-Shirts", "Formal Wear"],
  },
  {
    id: "3",
    name: "Kids",
    image: "/placeholder.svg?height=60&width=60",
    icon: "👶",
    subcategories: ["Boys", "Girls", "Infants", "School Wear"],
  },
  {
    id: "4",
    name: "Beauty & Personal care",
    image: "/placeholder.svg?height=60&width=60",
    icon: "💄",
    subcategories: ["Skincare", "Makeup", "Hair Care", "Fragrances"],
  },
  {
    id: "5",
    name: "Accessories",
    image: "/placeholder.svg?height=60&width=60",
    icon: "👜",
    subcategories: ["Bags", "Jewelry", "Watches", "Sunglasses"],
  },
  {
    id: "6",
    name: "Footwear",
    image: "/placeholder.svg?height=60&width=60",
    icon: "👟",
    subcategories: ["Sneakers", "Formal Shoes", "Sandals", "Boots"],
  },
  {
    id: "7",
    name: "Grocery & Kitchen",
    image: "/placeholder.svg?height=60&width=60",
    icon: "🍎",
    subcategories: ["Fresh Produce", "Pantry", "Kitchen Tools", "Appliances"],
  },
  {
    id: "8",
    name: "Household Essentials",
    image: "/placeholder.svg?height=60&width=60",
    icon: "🏠",
    subcategories: ["Cleaning", "Storage", "Decor", "Furniture"],
  },
  {
    id: "9",
    name: "Electronics",
    image: "/placeholder.svg?height=60&width=60",
    icon: "📱",
    subcategories: ["Phones", "Laptops", "Audio", "Gaming"],
  },
  {
    id: "10",
    name: "Sports & Fitness",
    image: "/placeholder.svg?height=60&width=60",
    icon: "⚽",
    subcategories: ["Gym Equipment", "Sports Wear", "Outdoor", "Yoga"],
  },
  {
    id: "11",
    name: "Books & Media",
    image: "/placeholder.svg?height=60&width=60",
    icon: "📚",
    subcategories: ["Fiction", "Non-Fiction", "Educational", "Comics"],
  },
  {
    id: "12",
    name: "Snakes & Drinks",
    image: "/placeholder.svg?height=60&width=60",
    icon: "🍿",
    subcategories: ["Beverages", "Snacks", "Healthy Options", "Party Packs"],
  },
]

// Add more products for different categories
export const products: Product[] = [
  // Men's products
  {
    id: "1",
    name: "Premium Cotton T-Shirt",
    description: "Comfortable and stylish cotton t-shirt perfect for everyday wear",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Men",
    inStock: true,
    rating: 4.5,
    reviews: 128,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "2",
    name: "Designer Jeans",
    description: "High-quality denim jeans with modern fit",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Men",
    inStock: true,
    rating: 4.3,
    reviews: 89,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "3",
    name: "Casual Hoodie",
    description: "Warm and comfortable hoodie for casual wear",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Men",
    inStock: true,
    rating: 4.4,
    reviews: 156,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "4",
    name: "Formal Shirt",
    description: "Professional formal shirt for office wear",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Men",
    inStock: true,
    rating: 4.6,
    reviews: 92,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "5",
    name: "Sports Jacket",
    description: "Lightweight sports jacket for active lifestyle",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Men",
    inStock: true,
    rating: 4.5,
    reviews: 73,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "6",
    name: "Cargo Pants",
    description: "Durable cargo pants with multiple pockets",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Men",
    inStock: true,
    rating: 4.2,
    reviews: 64,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  // Snakes & Drinks products
  {
    id: "7",
    name: "Energy Drink",
    description: "Refreshing energy drink to boost your day",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Snakes & Drinks",
    inStock: true,
    rating: 4.1,
    reviews: 45,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "8",
    name: "Protein Bars",
    description: "Healthy protein bars for fitness enthusiasts",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Snakes & Drinks",
    inStock: true,
    rating: 4.3,
    reviews: 67,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "9",
    name: "Mixed Nuts",
    description: "Premium quality mixed nuts for healthy snacking",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Snakes & Drinks",
    inStock: true,
    rating: 4.5,
    reviews: 89,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "10",
    name: "Fruit Juice",
    description: "Fresh and natural fruit juice blend",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Snakes & Drinks",
    inStock: true,
    rating: 4.4,
    reviews: 56,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "11",
    name: "Chocolate Cookies",
    description: "Delicious chocolate cookies for sweet cravings",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Snakes & Drinks",
    inStock: true,
    rating: 4.6,
    reviews: 78,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "12",
    name: "Green Tea",
    description: "Organic green tea for healthy lifestyle",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Snakes & Drinks",
    inStock: true,
    rating: 4.2,
    reviews: 34,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  // Women's products
  {
    id: "13",
    name: "Elegant Midi Dress",
    description: "Beautiful midi dress for special occasions",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Women",
    inStock: true,
    rating: 4.7,
    reviews: 156,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "14",
    name: "Casual Top",
    description: "Comfortable casual top for everyday wear",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Women",
    inStock: true,
    rating: 4.4,
    reviews: 92,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: "15",
    name: "Designer Jacket",
    description: "Stylish designer jacket for fashion-forward women",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Women",
    inStock: true,
    rating: 4.5,
    reviews: 123,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  // Kids products
  {
    id: "16",
    name: "Kids Casual Wear",
    description: "Comfortable and colorful clothing for kids",
    price: 150,
    image: "/placeholder.svg?height=300&width=300",
    category: "Kids",
    inStock: true,
    rating: 4.4,
    reviews: 67,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  // Add more products for other categories...
]

export const bannerImages = [
  {
    id: 1,
    image: "/download.png?height=500&width=1200",
    alt: "Banner Image 1",
  },
  {
    id: 2,
    image: "/download.png?height=500&width=1200",
    alt: "Banner Image 2",
  },
  {
    id: 3,
    image: "/download.png?height=500&width=1200",
    alt: "Banner Image 3",
  },
  {
    id: 4,
    image: "/download.png?height=500&width=1200",
    alt: "Banner Image 4",
  },
]
