import type { Product } from "./types"
import { Timestamp } from "firebase/firestore"


// Add more products for different categories
export const products: Product[] = [
    // Men's products
    {
        id: "1",
        name: "Premium Cotton T-Shirt",
        description: "Comfortable and stylish cotton t-shirt perfect for everyday wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        inStock: true,
        rating: 4.5,
        reviews: 128,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "2",
        name: "Designer Jeans",
        description: "High-quality denim jeans with modern fit",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        inStock: true,
        rating: 4.3,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "3",
        name: "Casual Hoodie",
        description: "Warm and comfortable hoodie for casual wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        inStock: true,
        rating: 4.4,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "4",
        name: "Formal Shirt",
        description: "Professional formal shirt for office wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        inStock: true,
        rating: 4.6,
        reviews: 92,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "5",
        name: "Sports Jacket",
        description: "Lightweight sports jacket for active lifestyle",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        inStock: true,
        rating: 4.5,
        reviews: 73,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "6",
        name: "Cargo Pants",
        description: "Durable cargo pants with multiple pockets",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        inStock: true,
        rating: 4.2,
        reviews: 64,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Snakes & Drinks products
    {
        id: "7",
        name: "Energy Drink",
        description: "Refreshing energy drink to boost your day",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snakes & Drinks",
        inStock: true,
        rating: 4.1,
        reviews: 45,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "8",
        name: "Protein Bars",
        description: "Healthy protein bars for fitness enthusiasts",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snakes & Drinks",
        inStock: true,
        rating: 4.3,
        reviews: 67,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "9",
        name: "Mixed Nuts",
        description: "Premium quality mixed nuts for healthy snacking",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snakes & Drinks",
        inStock: true,
        rating: 4.5,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "10",
        name: "Fruit Juice",
        description: "Fresh and natural fruit juice blend",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snakes & Drinks",
        inStock: true,
        rating: 4.4,
        reviews: 56,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "11",
        name: "Chocolate Cookies",
        description: "Delicious chocolate cookies for sweet cravings",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snakes & Drinks",
        inStock: true,
        rating: 4.6,
        reviews: 78,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "12",
        name: "Green Tea",
        description: "Organic green tea for healthy lifestyle",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snakes & Drinks",
        inStock: true,
        rating: 4.2,
        reviews: 34,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Women's products
    {
        id: "13",
        name: "Elegant Midi Dress",
        description: "Beautiful midi dress for special occasions",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        inStock: true,
        rating: 4.7,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "14",
        name: "Casual Top",
        description: "Comfortable casual top for everyday wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        inStock: true,
        rating: 4.4,
        reviews: 92,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "15",
        name: "Designer Jacket",
        description: "Stylish designer jacket for fashion-forward women",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        inStock: true,
        rating: 4.5,
        reviews: 123,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Kids products
    {
        id: "16",
        name: "Kids Casual Wear",
        description: "Comfortable and colorful clothing for kids",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Kids",
        inStock: true,
        rating: 4.4,
        reviews: 67,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Add more products for other categories...
]