import type { Product } from "./types"
import { Timestamp } from "firebase/firestore"


// Add more products for different categories
export const products: Product[] = [
    // Men's products
    {
        id: "1",
        name: "Premium Cotton T-Shirt",
        description: "Comfortable and stylish cotton t-shirt perfect for everyday wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "T-Shirts",
        inStock: true,
        rating: 4.5,
        reviews: 128,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "2",
        name: "Designer Jeans",
        description: "High-quality denim jeans with modern fit",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jeans",
        inStock: true,
        rating: 4.3,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "3",
        name: "Casual Hoodie",
        description: "Warm and comfortable hoodie for casual wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Hoodies",
        inStock: true,
        rating: 4.4,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "4",
        name: "Formal Shirt",
        description: "Professional formal shirt for office wear",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.6,
        reviews: 92,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "5",
        name: "Sports Jacket",
        description: "Lightweight sports jacket for active lifestyle",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.5,
        reviews: 73,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "6",
        name: "Cargo Pants",
        description: "Durable cargo pants with multiple pockets",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Pants",
        inStock: true,
        rating: 4.2,
        reviews: 64,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "7",
        name: "Slim Fit Chinos",
        description: "Versatile chinos perfect for smart casual occasions",
        price: 120,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Pants",
        inStock: true,
        rating: 4.3,
        reviews: 87,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "8",
        name: "Leather Jacket",
        description: "Premium leather jacket for a rugged look",
        price: 350,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.7,
        reviews: 145,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "9",
        name: "Polo Shirt",
        description: "Classic polo shirt for casual and semi-formal wear",
        price: 80,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.4,
        reviews: 112,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "10",
        name: "Wool Sweater",
        description: "Warm wool sweater perfect for winter",
        price: 180,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.6,
        reviews: 98,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "11",
        name: "Denim Jacket",
        description: "Classic denim jacket for layering",
        price: 140,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.5,
        reviews: 76,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "12",
        name: "Graphic T-Shirt",
        description: "Trendy graphic t-shirt with unique design",
        price: 60,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "13",
        name: "Track Pants",
        description: "Comfortable track pants for athletic activities",
        price: 90,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Pants",
        inStock: true,
        rating: 4.1,
        reviews: 68,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "14",
        name: "Blazer",
        description: "Smart blazer for professional occasions",
        price: 280,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.8,
        reviews: 56,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "15",
        name: "V-Neck T-Shirt",
        description: "Stylish v-neck t-shirt in soft cotton",
        price: 70,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "T-Shirts",
        inStock: true,
        rating: 4.3,
        reviews: 91,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "16",
        name: "Cardigan",
        description: "Cozy cardigan perfect for layering",
        price: 160,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.4,
        reviews: 82,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "17",
        name: "Joggers",
        description: "Comfortable joggers for casual wear",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Pants",
        inStock: true,
        rating: 4.2,
        reviews: 103,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "18",
        name: "Tank Top",
        description: "Basic tank top for summer wear",
        price: 45,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "T-Shirts",
        inStock: true,
        rating: 4.0,
        reviews: 127,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "19",
        name: "Windbreaker",
        description: "Lightweight windbreaker for outdoor activities",
        price: 110,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.3,
        reviews: 71,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "20",
        name: "Henley Shirt",
        description: "Casual henley shirt with button detail",
        price: 95,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.5,
        reviews: 84,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "21",
        name: "Dress Pants",
        description: "Formal dress pants for business wear",
        price: 220,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Pants",
        inStock: true,
        rating: 4.6,
        reviews: 59,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "22",
        name: "Flannel Shirt",
        description: "Cozy flannel shirt for casual comfort",
        price: 105,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.4,
        reviews: 96,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "23",
        name: "Zip-Up Hoodie",
        description: "Versatile zip-up hoodie for layering",
        price: 130,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Hoodies",
        inStock: true,
        rating: 4.3,
        reviews: 118,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "24",
        name: "Turtleneck Sweater",
        description: "Elegant turtleneck sweater for sophisticated look",
        price: 190,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.5,
        reviews: 73,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "25",
        name: "Skinny Jeans",
        description: "Modern skinny fit jeans with stretch",
        price: 140,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jeans",
        inStock: true,
        rating: 4.2,
        reviews: 108,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "26",
        name: "Bomber Jacket",
        description: "Stylish bomber jacket for urban style",
        price: 200,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.4,
        reviews: 85,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "27",
        name: "Long Sleeve Tee",
        description: "Basic long sleeve t-shirt in premium cotton",
        price: 75,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "T-Shirts",
        inStock: true,
        rating: 4.1,
        reviews: 142,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "28",
        name: "Shorts",
        description: "Comfortable shorts for summer activities",
        price: 65,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shorts",
        inStock: true,
        rating: 4.2,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "29",
        name: "Puffer Jacket",
        description: "Warm puffer jacket for cold weather",
        price: 250,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.6,
        reviews: 67,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "30",
        name: "Crew Neck Sweatshirt",
        description: "Classic crew neck sweatshirt for everyday wear",
        price: 115,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.3,
        reviews: 94,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "31",
        name: "Straight Leg Jeans",
        description: "Classic straight leg jeans with timeless fit",
        price: 135,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jeans",
        inStock: true,
        rating: 4.5,
        reviews: 121,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "32",
        name: "Oxford Shirt",
        description: "Premium oxford shirt for professional wear",
        price: 125,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.7,
        reviews: 78,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "33",
        name: "Swim Shorts",
        description: "Quick-dry swim shorts for beach activities",
        price: 55,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shorts",
        inStock: true,
        rating: 4.1,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "34",
        name: "Quarter Zip Pullover",
        description: "Stylish quarter zip pullover for layering",
        price: 145,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.4,
        reviews: 102,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "35",
        name: "Ripped Jeans",
        description: "Trendy ripped jeans for casual street style",
        price: 165,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jeans",
        inStock: true,
        rating: 4.0,
        reviews: 113,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "36",
        name: "Athletic Shorts",
        description: "Performance athletic shorts for workouts",
        price: 70,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shorts",
        inStock: true,
        rating: 4.3,
        reviews: 87,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "37",
        name: "Trench Coat",
        description: "Classic trench coat for rainy weather",
        price: 320,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.8,
        reviews: 43,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "38",
        name: "Muscle Tee",
        description: "Fitted muscle tee for athletic build",
        price: 50,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "T-Shirts",
        inStock: true,
        rating: 4.1,
        reviews: 95,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "39",
        name: "Cargo Shorts",
        description: "Utility cargo shorts with multiple pockets",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Shorts",
        inStock: true,
        rating: 4.2,
        reviews: 76,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "40",
        name: "Pullover Hoodie",
        description: "Comfortable pullover hoodie with front pocket",
        price: 125,
        image: "/placeholder.svg?height=300&width=300",
        category: "Men",
        subcategory: "Hoodies",
        inStock: true,
        rating: 4.4,
        reviews: 139,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },

    // Snacks & Drinks products
    {
        id: "41",
        name: "Energy Drink",
        description: "Refreshing energy drink to boost your day",
        price: 25,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.1,
        reviews: 45,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "42",
        name: "Protein Bars",
        description: "Healthy protein bars for fitness enthusiasts",
        price: 35,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Bars",
        inStock: true,
        rating: 4.3,
        reviews: 67,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "43",
        name: "Mixed Nuts",
        description: "Premium quality mixed nuts for healthy snacking",
        price: 40,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Nuts",
        inStock: true,
        rating: 4.5,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "44",
        name: "Fruit Juice",
        description: "Fresh and natural fruit juice blend",
        price: 30,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.4,
        reviews: 56,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "45",
        name: "Chocolate Cookies",
        description: "Delicious chocolate cookies for sweet cravings",
        price: 20,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Cookies",
        inStock: true,
        rating: 4.6,
        reviews: 78,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "46",
        name: "Green Tea",
        description: "Organic green tea for healthy lifestyle",
        price: 15,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Tea",
        inStock: true,
        rating: 4.2,
        reviews: 34,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "47",
        name: "Potato Chips",
        description: "Crispy potato chips with classic salt flavor",
        price: 12,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Chips",
        inStock: true,
        rating: 4.0,
        reviews: 125,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "48",
        name: "Granola Bars",
        description: "Nutritious granola bars with oats and honey",
        price: 28,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Bars",
        inStock: true,
        rating: 4.3,
        reviews: 92,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "49",
        name: "Sparkling Water",
        description: "Refreshing sparkling water with natural flavors",
        price: 18,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.1,
        reviews: 73,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "50",
        name: "Trail Mix",
        description: "Healthy trail mix with nuts, seeds, and dried fruits",
        price: 35,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Nuts",
        inStock: true,
        rating: 4.4,
        reviews: 68,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "51",
        name: "Iced Coffee",
        description: "Cold brew iced coffee for coffee lovers",
        price: 22,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Coffee",
        inStock: true,
        rating: 4.5,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "52",
        name: "Pretzels",
        description: "Crunchy salted pretzels for snacking",
        price: 15,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Chips",
        inStock: true,
        rating: 4.2,
        reviews: 84,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "53",
        name: "Herbal Tea",
        description: "Calming herbal tea blend for relaxation",
        price: 16,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Tea",
        inStock: true,
        rating: 4.3,
        reviews: 47,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "54",
        name: "Beef Jerky",
        description: "Premium beef jerky for protein-rich snacking",
        price: 45,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Jerky",
        inStock: true,
        rating: 4.6,
        reviews: 103,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "55",
        name: "Coconut Water",
        description: "Natural coconut water for hydration",
        price: 20,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.2,
        reviews: 61,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "56",
        name: "Oatmeal Cookies",
        description: "Homestyle oatmeal cookies with raisins",
        price: 18,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Cookies",
        inStock: true,
        rating: 4.4,
        reviews: 76,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "57",
        name: "Almonds",
        description: "Roasted almonds with sea salt",
        price: 32,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Nuts",
        inStock: true,
        rating: 4.5,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "58",
        name: "Sports Drink",
        description: "Electrolyte sports drink for active lifestyle",
        price: 24,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.1,
        reviews: 94,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "59",
        name: "Cheese Crackers",
        description: "Crispy cheese crackers for snacking",
        price: 14,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Crackers",
        inStock: true,
        rating: 4.0,
        reviews: 112,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "60",
        name: "Smoothie",
        description: "Fruit smoothie blend with vitamins",
        price: 28,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.3,
        reviews: 87,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "61",
        name: "Popcorn",
        description: "Buttery popcorn for movie nights",
        price: 10,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Popcorn",
        inStock: true,
        rating: 4.2,
        reviews: 139,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "62",
        name: "Cashews",
        description: "Premium roasted cashews",
        price: 38,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Nuts",
        inStock: true,
        rating: 4.6,
        reviews: 95,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "63",
        name: "Chocolate Bar",
        description: "Dark chocolate bar with 70% cocoa",
        price: 16,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Chocolate",
        inStock: true,
        rating: 4.7,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "64",
        name: "Lemonade",
        description: "Fresh squeezed lemonade drink",
        price: 19,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.1,
        reviews: 71,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "65",
        name: "Rice Cakes",
        description: "Light and crispy rice cakes",
        price: 13,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Cakes",
        inStock: true,
        rating: 4.0,
        reviews: 58,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "66",
        name: "Dried Fruit",
        description: "Mix of dried fruits for healthy snacking",
        price: 25,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Fruits",
        inStock: true,
        rating: 4.3,
        reviews: 82,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "67",
        name: "Iced Tea",
        description: "Refreshing iced tea with lemon",
        price: 17,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Tea",
        inStock: true,
        rating: 4.2,
        reviews: 96,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "68",
        name: "Peanut Butter",
        description: "Creamy peanut butter spread",
        price: 22,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Spreads",
        inStock: true,
        rating: 4.5,
        reviews: 118,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "69",
        name: "Tortilla Chips",
        description: "Crispy tortilla chips with lime",
        price: 15,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Chips",
        inStock: true,
        rating: 4.1,
        reviews: 107,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "70",
        name: "Kombucha",
        description: "Probiotic kombucha for digestive health",
        price: 26,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.4,
        reviews: 64,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "71",
        name: "Gummy Bears",
        description: "Fruity gummy bears candy",
        price: 12,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Candy",
        inStock: true,
        rating: 4.0,
        reviews: 145,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "72",
        name: "Pistachios",
        description: "Salted pistachios in shells",
        price: 42,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Nuts",
        inStock: true,
        rating: 4.5,
        reviews: 78,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "73",
        name: "Protein Shake",
        description: "Ready-to-drink protein shake",
        price: 35,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 4.2,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "74",
        name: "Veggie Chips",
        description: "Baked vegetable chips mix",
        price: 18,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Chips",
        inStock: true,
        rating: 4.1,
        reviews: 65,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "75",
        name: "Mint Tea",
        description: "Refreshing mint tea for digestion",
        price: 14,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Tea",
        inStock: true,
        rating: 4.3,
        reviews: 52,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "76",
        name: "Fruit Snacks",
        description: "Natural fruit snacks for kids and adults",
        price: 16,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Fruits",
        inStock: true,
        rating: 4.2,
        reviews: 91,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "77",
        name: "Energy Balls",
        description: "Homemade energy balls with dates and nuts",
        price: 24,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Bars",
        inStock: true,
        rating: 4.4,
        reviews: 73,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "78",
        name: "Soda Water",
        description: "Plain soda water for mixing",
        price: 8,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Drinks",
        inStock: true,
        rating: 3.9,
        reviews: 84,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "79",
        name: "Sunflower Seeds",
        description: "Roasted sunflower seeds with salt",
        price: 11,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Seeds",
        inStock: true,
        rating: 4.1,
        reviews: 106,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "80",
        name: "Matcha Latte",
        description: "Premium matcha latte drink",
        price: 29,
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks & Drinks",
        subcategory: "Coffee",
        inStock: true,
        rating: 4.6,
        reviews: 67,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Women's products
    {
        id: "81",
        name: "Elegant Midi Dress",
        description: "Beautiful midi dress for special occasions",
        price: 180,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Dresses",
        inStock: true,
        rating: 4.7,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "82",
        name: "Casual Blouse",
        description: "Comfortable casual blouse for everyday wear",
        price: 95,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Tops",
        inStock: true,
        rating: 4.4,
        reviews: 92,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "83",
        name: "Designer Blazer",
        description: "Stylish designer blazer for fashion-forward women",
        price: 220,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.5,
        reviews: 123,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "84",
        name: "Skinny Jeans",
        description: "Trendy skinny jeans with stretch fabric",
        price: 145,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Jeans",
        inStock: true,
        rating: 4.3,
        reviews: 187,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "85",
        name: "Silk Scarf",
        description: "Luxury silk scarf with floral pattern",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.6,
        reviews: 78,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "86",
        name: "High-Waisted Pants",
        description: "Elegant high-waisted pants for professional wear",
        price: 125,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Pants",
        inStock: true,
        rating: 4.4,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "87",
        name: "Cardigan Sweater",
        description: "Cozy cardigan sweater perfect for layering",
        price: 110,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.5,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "88",
        name: "Floral Sundress",
        description: "Light and breezy floral sundress for summer",
        price: 95,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Dresses",
        inStock: true,
        rating: 4.3,
        reviews: 98,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "89",
        name: "Leather Handbag",
        description: "Premium leather handbag with multiple compartments",
        price: 185,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Bags",
        inStock: true,
        rating: 4.8,
        reviews: 245,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "90",
        name: "Pencil Skirt",
        description: "Classic pencil skirt for office wear",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Skirts",
        inStock: true,
        rating: 4.2,
        reviews: 167,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "91",
        name: "Yoga Pants",
        description: "Comfortable yoga pants for exercise and lounging",
        price: 65,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Activewear",
        inStock: true,
        rating: 4.4,
        reviews: 289,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "92",
        name: "Wrap Dress",
        description: "Flattering wrap dress suitable for any occasion",
        price: 135,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Dresses",
        inStock: true,
        rating: 4.6,
        reviews: 203,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "93",
        name: "Crossbody Bag",
        description: "Stylish crossbody bag for hands-free convenience",
        price: 75,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Bags",
        inStock: true,
        rating: 4.3,
        reviews: 145,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "94",
        name: "Maxi Dress",
        description: "Elegant maxi dress for evening events",
        price: 165,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Dresses",
        inStock: true,
        rating: 4.5,
        reviews: 178,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "95",
        name: "Denim Jacket",
        description: "Classic denim jacket for casual styling",
        price: 105,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.4,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "96",
        name: "V-Neck Sweater",
        description: "Soft v-neck sweater in premium wool",
        price: 95,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.3,
        reviews: 123,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "97",
        name: "High Heels",
        description: "Elegant high heels for formal occasions",
        price: 125,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Shoes",
        inStock: true,
        rating: 4.2,
        reviews: 189,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "98",
        name: "Pleated Skirt",
        description: "Stylish pleated skirt with flowing fabric",
        price: 90,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Skirts",
        inStock: true,
        rating: 4.4,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "99",
        name: "Leather Jacket",
        description: "Edgy leather jacket for a bold look",
        price: 285,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.7,
        reviews: 167,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "100",
        name: "Tote Bag",
        description: "Spacious tote bag for everyday use",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Bags",
        inStock: true,
        rating: 4.3,
        reviews: 198,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "101",
        name: "Camisole Top",
        description: "Delicate camisole top for layering",
        price: 45,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Tops",
        inStock: true,
        rating: 4.1,
        reviews: 87,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "102",
        name: "Wide-Leg Pants",
        description: "Trendy wide-leg pants for a relaxed fit",
        price: 115,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Pants",
        inStock: true,
        rating: 4.4,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "103",
        name: "Clutch Purse",
        description: "Elegant clutch purse for evening events",
        price: 65,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Bags",
        inStock: true,
        rating: 4.5,
        reviews: 123,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "104",
        name: "Cashmere Scarf",
        description: "Luxurious cashmere scarf for winter warmth",
        price: 145,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.8,
        reviews: 89,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "105",
        name: "A-Line Skirt",
        description: "Flattering A-line skirt in versatile colors",
        price: 75,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Skirts",
        inStock: true,
        rating: 4.3,
        reviews: 145,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "106",
        name: "Trench Coat",
        description: "Classic trench coat for rainy days",
        price: 195,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.6,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "107",
        name: "Ankle Boots",
        description: "Stylish ankle boots for fall fashion",
        price: 135,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Shoes",
        inStock: true,
        rating: 4.4,
        reviews: 178,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "108",
        name: "Silk Blouse",
        description: "Elegant silk blouse for professional wear",
        price: 155,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Tops",
        inStock: true,
        rating: 4.5,
        reviews: 167,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "109",
        name: "Palazzo Pants",
        description: "Flowing palazzo pants for comfort and style",
        price: 95,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Pants",
        inStock: true,
        rating: 4.2,
        reviews: 123,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "110",
        name: "Statement Necklace",
        description: "Bold statement necklace to elevate any outfit",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.3,
        reviews: 98,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "111",
        name: "Bodycon Dress",
        description: "Form-fitting bodycon dress for night out",
        price: 105,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Dresses",
        inStock: true,
        rating: 4.1,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "112",
        name: "Wool Coat",
        description: "Warm wool coat for winter elegance",
        price: 245,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Jackets",
        inStock: true,
        rating: 4.7,
        reviews: 145,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "113",
        name: "Sports Bra",
        description: "Supportive sports bra for active lifestyle",
        price: 45,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Activewear",
        inStock: true,
        rating: 4.4,
        reviews: 234,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "114",
        name: "Denim Skirt",
        description: "Classic denim skirt for casual wear",
        price: 70,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Skirts",
        inStock: true,
        rating: 4.2,
        reviews: 189,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "115",
        name: "Backpack",
        description: "Stylish backpack for work and travel",
        price: 95,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Bags",
        inStock: true,
        rating: 4.3,
        reviews: 167,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "116",
        name: "Peplum Top",
        description: "Flattering peplum top for feminine silhouette",
        price: 75,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Tops",
        inStock: true,
        rating: 4.4,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "117",
        name: "Cropped Pants",
        description: "Stylish cropped pants for versatile styling",
        price: 85,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Pants",
        inStock: true,
        rating: 4.2,
        reviews: 156,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "118",
        name: "Oversized Sweater",
        description: "Cozy oversized sweater for relaxed comfort",
        price: 125,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Sweaters",
        inStock: true,
        rating: 4.5,
        reviews: 178,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "119",
        name: "Ballet Flats",
        description: "Comfortable ballet flats for everyday wear",
        price: 65,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Shoes",
        inStock: true,
        rating: 4.1,
        reviews: 245,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: "120",
        name: "Shift Dress",
        description: "Classic shift dress for office and casual wear",
        price: 115,
        image: "/placeholder.svg?height=300&width=300",
        category: "Women",
        subcategory: "Dresses",
        inStock: true,
        rating: 4.3,
        reviews: 167,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Kids products
    {
        id: "121",
        name: "Kids Casual Wear",
        description: "Comfortable and colorful clothing for kids",
        price: 150,
        image: "/placeholder.svg?height=300&width=300",
        category: "Kids",
        subcategory: "Casual Wear",
        inStock: true,
        rating: 4.4,
        reviews: 67,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    // Add more products for other categories...
]