import type { Product } from "./types"
import { Timestamp } from "firebase/firestore"

// Function to generate a unique alphanumeric ID
const generateAlphanumericId = (length: number = 10): string => {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    const charactersLength = characters.length;
    for (let i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
};

// Add more products for different categories
export const products: Product[] = [
    // Men's products
    {
        id: generateAlphanumericId(), // Alphanumeric ID generated here
        name: "Campus Sutra",
        description: "Men's Ash Grey & Midnight Black Wave-Ombre Shirt",
        price: 949,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476977/Menshirt1_uobrrv.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.3,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Campus Sutra",
        description: "Men's Mustard Yellow Solid Lustre Shirt",
        price: 949,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476977/Menshirt2_n7quaw.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.4,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "SNITCH",
        description: "Snitch Mens Shirtolo Plain Navy Shirt",
        price: 1199,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476977/Menshirt3_dzo3zy.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.0,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "SNITCH",
        description: "Slim Fit Stretch Stripes Black Luxe Shirt",
        price: 699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476977/Menshirt4_jjn6ks.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 1,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Cotton Linen Stripes",
        description: "Nautical Cotton Linen Shirts",
        price: 1499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476980/Menshirt5_uqypi0.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.1,
        reviews: 1,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Solids Mystic Black Men Utility Shirts",
        price: 1699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476978/Menshirt6_j8movf.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Cotton Linen Dark Grey - Cotton Linen Shirts",
        price: 1499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476978/Menshirt7_mi3oae.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 3.9,
        reviews: 7,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Pearl White Cotton Linen Shirts",
        price: 1599,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476980/Menshirt8_g0d4wf.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 10,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "The Last Shogun Oversized Shirts",
        price: 1599,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476985/Menshirt9_ith59r.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.3,
        reviews: 20,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Hawaiian Shirt: State Of Mind - Holiday Shirts",
        price: 1699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752476984/Menshirt10_i1wesh.jpg",
        category: "Men",
        subcategory: "Shirts",
        inStock: true,
        rating: 4.0,
        reviews: 1,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Pronk",
        description: "Parachute Pants For Men - Olive Green",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477152/Bottonwear1_g0c6yj.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 3.9,
        reviews: 2,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Hubberholme",
        description: "Hubberholme Men Clean Look Relaxed Fit Stretchable Joggers",
        price: 1569,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477152/Bottonwear2_zsmswj.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4,
        reviews: 6,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Baggy Cargo Denims: Arctic",
        price: 1199,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477152/Bottonwear3_erionp.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4,
        reviews: 4,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "WHAT THE FLEX",
        description: "GREY Parachute Pants",
        price: 1399,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477153/Bottonwear4_qcvv3k.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 3.3,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Pronk",
        description: "Mens Twill Shorts - Classic Navy",
        price: 699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477153/Bottonwear5_lis6kr.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4.1,
        reviews: 3,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Sweatshirt",
        description: "Regular Fit Basic Shorts, BLACK",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477158/Bottonwear6_pxtmqf.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4.3,
        reviews: 5,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "House of Koala",
        description: "Unisex Grey Baggy Fit Mid Rise Pure Cotton Cargos Trousers",
        price: 1299,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477161/Bottonwear7_mm9xui.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4.8,
        reviews: 56,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Bene Kleed",
        description: "Men Loose Fit High-Rise Cargo Trouser",
        price: 1399,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477162/Bottonwear8_ssiffz.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4.4,
        reviews: 2,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Pant Project",
        description: "Grey Checks Power-Stretch Pants",
        price: 1549,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477163/Bottonwear9_gsshio.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4,
        reviews: 5,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Pant Project",
        description: "Mineral Grey Stretch Pants",
        price: 1599,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477167/Bottonwear10_jixln4.jpg",
        category: "Men",
        subcategory: "Bottomwear",
        inStock: true,
        rating: 4,
        reviews: 7,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Campus Sutra",
        description: "Men's Lilac Breezy Wrinkled Shirt",
        price: 949,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477307/Topwear1_q7lv4o.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4,
        reviews: 1,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Pronk",
        description: "Mens Half Sleeve Resort Shirt - Black",
        price: 849,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477307/Topwear2_zp9za8.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4.3,
        reviews: 1,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "House of Koala",
        description: "House of Koala Unisex Textured Oversized Polo Neck T-shirt",
        price: 699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477308/Topwear3_jmfztv.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 3.2,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "VEIRDO",
        description: "Go Veirdo Brown Pocket Graphic Printed Oversized Tshirt",
        price: 449,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477308/Topwear4_esipsp.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4.2,
        reviews: 44,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Pronk",
        description: "One Life Men Premium Oversized Terry T-shirt",
        price: 799,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477308/Topwear5_sknaos.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4.2,
        reviews: 4,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Campus Sutra",
        description: "Men's Ash Grey Heathered Cuban Relaxed Shirt",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477314/Topwear6_cqfj2b.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 3.1,
        reviews: 3,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "SILISOUL",
        description:
            "Men Flannel check Premium Shirt, Regular Fit, Pure Cotton, Blue-Orange",
        price: 1099,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477315/Topwear7_eswosz.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 5,
        reviews: 1,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Campus Sutra",
        description: "Men's Mint Green & Daisy White Abstract-Deco Regular Shirt",
        price: 949,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477321/Topwear8_rzakrn.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4.4,
        reviews: 0,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Jurassic World: T-Rex Footprint - Oversized T-Shirts ",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477321/Topwear9_jhp8ug.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4.2,
        reviews: 48,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Henley T-Shirt",
        description: "Casual henley t-shirt with button placket",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477322/Topwear10_ocooax.jpg",
        category: "Men",
        subcategory: "Topwear",
        inStock: true,
        rating: 4.3,
        reviews: 63,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Marvel: Punisher- Boxer Shorts",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477449/Innerwear1_h9htfq.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.2,
        reviews: 41,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Denim Shorts Shadow Black Men Denim Shorts",
        price: 699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477450/Innerwear2_vx465o.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.4,
        reviews: 52,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Stores",
        description: "Joker Mayhem State Boxer Shorts",
        price: 399,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477450/Innerwear2_vx465o.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.2,
        reviews: 41,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Minions",
        description: "Minion Fun Boxer Shorts",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477451/Innerwear4_gfhhcq.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.7,
        reviews: 29,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Solids: ",
        description: "Popeye Sailor Legend Boxer Shorts",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477453/Innerwear5_njozyh.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.3,
        reviews: 66,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Denim",
        description: "olids: Sea Lettuce Men Cargo Shorts",
        price: 899,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477459/Innerwear6_r7y4bu.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.4,
        reviews: 58,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Denim: ",
        description: "Blue Cloud Men Denim Shorts",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477460/Innerwear7_hictuv.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.6,
        reviews: 47,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Denim",
        description: "Blue Cloud Men Denim Shorts",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477462/Innerwear8_whtvpp.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.3,
        reviews: 62,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Denim Shorts",
        description: " Gunmetal Men Denim Shorts",
        price: 1299,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477468/Innerwear9_k0uebb.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.2,
        reviews: 38,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store Denim",
        description: " Ink Blue Men Denim Shorts",
        price: 1099,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477471/Innerwear10_giz0mh.jpg",
        category: "Men",
        subcategory: "Innerwear",
        inStock: true,
        rating: 4.1,
        reviews: 44,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Black Solid Dyed Kurta",
        price: 2999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477574/EthnicFusionWear1_s2z6rd.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Off White Printed Kurta",
        price: 2499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477575/EthnicFusionWear2_sejiep.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Navy Blue Embroidered Kurta Trouser Set",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477575/EthnicFusionWear3_hjfzqj.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Black Jacquard Nehru Jacket",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477575/EthnicFusionWear4_njva1g.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Black Embroidered Kurta",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477585/EthnicFusionWear5_kzmcdh.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Black Embroidered Nehru Jacket",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477583/EthnicFusionWear6_fdbuhj.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Prakatha",
        description: "Yellow Thread Sequence And Embroidered Kurta For Men",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477584/EthnicFusionWear7_kgqx30.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "ADWYN PETER",
        description: "Adwyn peter men's Embroidery Kurta: Blue",
        price: 799,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477584/EthnicFusionWear8_w0qqxn.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Green Embroidered Kurta Nehru Jacket Churidar Set",
        price: 2999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477585/EthnicFusionWear9_hwbxdr.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "KISAH",
        description: "Men's Purple Jacquard Sherwani Trouser Set",
        price: 4499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477594/EthnicFusionWear10_adrgfj.jpg",
        category: "Men",
        subcategory: "Ethnic & Fusion Wear",
        inStock: true,
        rating: 4.4,
        reviews: 77,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "OFF DUTY INDIA",
        description: "Ancient Cross Culture Premium T-Shirt",
        price: 590,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477803/MenTshirt1_pvrbys.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "OFF DUTY INDIA",
        description: "Off-Duty Raceway Premium T-Shirt",
        price: 590,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477803/MenTshirt2_rtpuhe.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "WHAT THE FLEX",
        description: "MIRACLES Heavyweight T-shirt",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477804/MenTshirt3_lh0wr9.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "WHAT THE FLEX UNFOLLOW THE WORLD ",
        description: "Heavyweight T-shirt",
        price: 599,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477811/MenTshirt4_yjvlth.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "WHAT THE FLEX",
        description: "Body Bones Heavyweight T-Shirt",
        price: 599,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477812/MenTshirt5_gjq7n6.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "WHAT THE FLEX DREAMERS & REBELS ",
        description: "Heavyweight T-shirt",
        price: 599,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477813/MenTshirt6_ck2k4m.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "SNITCH",
        description: "Waves Navy Printed Oversized T-Shirt",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477813/MenTshirt7_fywje2.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "TOne Piece: Pirates",
        price: 799,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477820/MenTshirt8_apohmh.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store ",
        description: "Nirvana Oversized T-Shirts",
        price: 1199,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477819/MenTshirt9_obyswz.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Samsara Super Oversized T-Shirts",
        price: 1299,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477822/MenTshirt10_o4cmcw.jpg",
        category: "Men",
        subcategory: "Graphic T-Shirts",
        inStock: true,
        rating: 4.2,
        reviews: 134,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Batman: Gotham Gear Backpacks",
        price: 2499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477946/AccessoriesM1_qq3vzh.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Harry Potter: Slytherin Backpacks",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477947/AccessoriesM2_b3fqib.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Jurassic Park: Camo Caps",
        price: 399,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477948/AccessoriesM3_xr2jkf.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Spider-Man: Web-Slinger Caps",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477948/AccessoriesM4_jrdmoo.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Sylvi",
        description: "Prototype Gazedoom RoseCrown Strap: Coffee Silicone 3d Doom Glass, Date-Day Display, Stopwatch, Chronograph, Analog Design",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477954/AccessoriesM5_jtx5h9.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Sylvi",
        description: "Prototype Gazedoom IvoryGleam Strap: Black Silicone, Ideal for: Me 3d Doom Glass, Date-Day Display, Stopwatch, Chronograph, Analog Design",
        price: 999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477957/AccessoriesM6_rqr3ml.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Labnoft",
        description: "Labnoft Men's PU Leather Auto-Lock Belt",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752477963/AccessoriesM7_zcr8r3.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Labnoft",
        description: "abnoft Men's PU Leather Auto-Lock Belt",
        price: 699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478013/AccessoriesM8_p8ompo.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Squid Game: 456 Socks",
        price: 199,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478019/AccessoriesM9_asso0b.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Looney Tunes: Bugs Bunny Socks",
        price: 199,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478031/AccessoriesM10_soecjv.jpg",
        category: "Men",
        subcategory: "Accessories",
        inStock: true,
        rating: 4.5,
        reviews: 88,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "GULLY LABS",
        description: "GULLY NUMBER 001 - BAAZ FARIS BLACK",
        price: 1499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478186/FootwearMen1_aij2qe.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },

    {
        id: generateAlphanumericId(),
        name: "Monkstory",
        description: "T-Rad Classic Double Monk Strap Sandals ",
        price: 699,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478187/FootwearMen2_hvfztv.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Yoho",
        description: "YOHO PILO Slippers for Men| Durable| Lightweight| Daily| Waterproof l Stylish l Comfortable",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478187/FootwearMen3_c2uouv.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },

    {
        id: generateAlphanumericId(),
        name: "Yoho",
        description: "YOHO PILO Slippers for Men| Durable| Lightweight| Daily| Waterproof l Stylish l Comfortable",
        price: 499,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478194/FootwearMen4_bhppzj.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
    {
        id: generateAlphanumericId(),
        name: "Monkstory",
        description: "T-Rad Luxe Horsebit Sandals - Brown",
        price: 1290,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478194/FootwearMen5_rv0pcc.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },

    {
        id: generateAlphanumericId(),
        name: "Planet Paaduks",
        description: "Paaduks Leo Crossover Vegan Leather Brown Men Sandals",
        price: 986,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478195/FootwearMen6_f5uotu.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    }, {
        id: generateAlphanumericId(),
        name: "Monkstory",
        description: "Monkstory Horsebit Croc-Effect Slip-Ons - Black",
        price: 1890,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478199/FootwearMen7_obmtll.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },

    {
        id: generateAlphanumericId(),
        name: "Monkstory",
        description: "Glossy Classic Patent Lace-Ups - Black",
        price: 2090,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478206/FootwearMen8_uxomdx.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    }, {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Souled: Autumn Men Low Top Sneakers",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478200/FootwearMen9_hzl966.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },

    {
        id: generateAlphanumericId(),
        name: "The Souled Store",
        description: "Souled: RCVR Men Low Top Sneakers",
        price: 1999,
        image: "https://res.cloudinary.com/wishwell/image/upload/v1752478202/FootwearMen10_rujwff.jpg",
        category: "Men",
        subcategory: "Footwear",
        inStock: true,
        rating: 4.6,
        reviews: 110,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    },
];